# Generated by Django 5.0.1 on 2024-02-04 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('therapist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('specialization', models.CharField(max_length=100)),
                ('availability', models.CharField(blank=True, choices=[('A', 'Available'), ('B', 'BOOKED')], default='Available', help_text='Confirm Availability', max_length=10)),
            ],
            options={
                'ordering': ['therapist_id'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('contact', models.CharField(max_length=15)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.appointment')),
            ],
            options={
                'ordering': ['patient_id'],
            },
        ),
    ]
