# Generated by Django 5.0.1 on 2024-02-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_patient_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['patient_id'], 'permissions': [('can_add_appointment', 'Can add appointment')]},
        ),
        migrations.AlterModelOptions(
            name='therapist',
            options={'ordering': ['therapist_id'], 'permissions': [('can_mark_available', 'Set therapist as available'), ('can_mark_booked', 'Set therapist as booked')]},
        ),
    ]
