# Generated by Django 5.0.1 on 2024-02-12 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_patient_therapist_alter_therapist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.therapist'),
        ),
    ]
