# Generated by Django 5.0.1 on 2024-02-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_patient_therapist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='therapist',
        ),
    ]
