# Generated by Django 5.0.1 on 2024-02-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_therapist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.CharField(blank=True, help_text='Type of Service Sought After', max_length=100, null=True),
        ),
    ]
