# Generated by Django 5.0.1 on 2024-02-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_patient_therapist_alter_therapist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
    ]
