# Generated by Django 5.0.1 on 2024-02-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_appointment_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='specialization',
            field=models.CharField(blank=True, choices=[('COUPLES', 'COUPLES'), ('TRAUMA', 'TRAUMA'), ('DEPRESSION', 'DEPRESSION'), ('NUTRITIONAL', 'NUTRITIONAL'), ('FAMILY', 'FAMILY'), ('BEHAVIORAL', 'BEHAVIORAL'), ('ADDICTION', 'ADDICTION')], help_text='Select Specialization', max_length=100),
        ),
    ]
