# Generated by Django 5.0.1 on 2024-02-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_therapist_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(blank=True, choices=[('COUPLES', 'COUPLES'), ('TRAUMA', 'TRAUMA'), ('DEPRESSION', 'DEPRESSION'), ('NUTRITIONAL', 'NUTRITIONAL'), ('FAMILY', 'FAMILY'), ('BEHAVIORAL', 'BEHAVIORAL'), ('ADDICTION', 'ADDICTION')], help_text='Select Specialization', max_length=100),
        ),
    ]
