# Generated by Django 5.0.1 on 2024-02-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_alter_appointment_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['name'], 'permissions': [('can_update_patient', 'Update patient details'), ('can_delete_patient', 'Delete patient'), ('can_view_patient', 'View patient details'), ('can_create_patient', 'Create patient'), ('can_view_all therapists', 'View all therapists')]},
        ),
        migrations.AlterModelOptions(
            name='therapist',
            options={'ordering': ['name', 'specialization'], 'permissions': [('can_mark_available', 'Set therapist as available'), ('can_mark_booked', 'Set therapist as booked'), ('can_view_all_appointments', 'View all appointments'), ('can_view_appointment', 'View appointment details'), ('can_view_therapist', 'View therapist details'), ('can_view_patient', 'View patient details'), ('can_view_all_patients', 'View all patients'), ('can_view_all_therapists', 'View all therapists'), ('can_view_therapist_dashboard', 'View therapist dashboard'), ('can_view_appointment_list', 'View appointment list'), ('can_view_patient_list', 'View patient list'), ('can_view_therapist_list', 'View therapist list'), ('can_view_appointment_detail', 'View appointment details'), ('can_view_patient_detail', 'View patient details'), ('can_view_therapist_detail', 'View therapist details'), ('can_view_appointment_create', 'Create appointment'), ('can_view_patient_create', 'Create patient'), ('can_view_therapist_create', 'Create therapist'), ('can_view_appointment_update', 'Update appointment'), ('can_view_patient_update', 'Update patient'), ('can_view_therapist_update', 'Update therapist'), ('can_view_appointment_delete', 'Delete appointment'), ('can_view_patient_delete', 'Delete patient'), ('can_view_therapist_delete', 'Delete therapist')]},
        ),
    ]
